// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var ONE_DAY;
    ONE_DAY = 1000 * 60 * 60 * 24;
    window.initCountryList = function() {
      var $countrySelect, optionsFrag;
      $countrySelect = $('#country');
      optionsFrag = document.createDocumentFragment();
      $.each(expectancy, function(index, el) {
        var country, option;
        country = el.country;
        option = document.createElement('option');
        option.value = country;
        option.innerText = country;
        return optionsFrag.appendChild(option);
      });
      return $countrySelect.append(optionsFrag);
    };
    window.getLifeExpectancyForCountry = function(country) {
      var countries;
      countries = expectancy.filter(function(el) {
        return el.country === country;
      });
      return countries[0];
    };
    window.parseDate = function(date) {
      var ymd;
      ymd = date.split('-');
      return new Date(ymd[0], ymd[1] - 1, ymd[2]);
    };
    window.getDaysLived = function(birthdate) {
      var birth, now;
      birth = parseDate(birthdate);
      now = new Date();
      return Math.floor((now - birth) / ONE_DAY);
    };
    window.getDaysToLive = function(countryExpectancy, genre, daysLived) {
      var daysExpected;
      daysExpected = Math.floor(countryExpectancy[genre] * 365);
      return daysExpected - daysLived;
    };
    window.calculateLifePercentage = function(countryExpectancy, genre, daysLived) {
      var daysExpected;
      daysExpected = Math.floor(countryExpectancy[genre] * 365);
      return parseFloat(100 - (((daysLived / daysExpected) * 100).toFixed(2)));
    };
    window.calculateLifeStats = function(genre, country, birthdate) {
      var countryExpectancy, daysLived, daysToLive, remainingPercent;
      countryExpectancy = getLifeExpectancyForCountry(country);
      daysLived = getDaysLived(birthdate);
      daysToLive = getDaysToLive(countryExpectancy, genre, daysLived);
      remainingPercent = calculateLifePercentage(countryExpectancy, genre, daysLived);
      return {
        daysLived: daysLived,
        daysToLive: daysToLive,
        remainingPercent: remainingPercent
      };
    };
    window.calculateLifeLeft = function(ev) {
      var $form, birthdate, country, genre, stats;
      ev.preventDefault();
      $form = $(this);
      genre = $form.find('#genre').val();
      country = $form.find('#country').val();
      birthdate = $form.find('#birthdate').val();
      if (genre.length > 0 && country.length > 0 && birthdate.length > 0) {
        stats = calculateLifeStats(genre, country, birthdate);
        return console.log("Days lived: " + stats.daysLived + "; Days to live: " + stats.daysToLive + "; Life left: " + stats.remainingPercent + "%");
      }
    };
    initCountryList();
    return $('#life-form').on('submit', calculateLifeLeft);
  });

}).call(this);
